[tool.black]
line-length = 88
target-version = ['py37']
include = '\.pyi?$'
exclude = '''
(
  /(
      examples
    | \.git
    | \.mypy_cache
    | \.pytest_cache
    | \.venv
    | build
    | dist
  )/
)
'''

[tool.isort]
line_length = 88
multi_line_output = 3
include_trailing_comma = true
