#!/usr/bin/env bash

# Quick and simple build script for the project.

. "$(dirname "${0}")/common" || { echo ERROR; exit 1; }

# $*: Message files to build
build_messages() {
    mkdir -p "${PROTOC_DST_DIR}"/{js,python}

    echo -e '\e[1;37m'"Building ${@}..."'\e[0m'

    protoc \
        --proto_path=messages \
        --python_out="${PROTOC_DST_DIR}/python" \
        --js_out="${PROTOC_DST_DIR}/js" \
        "${@}"

    return $?
}

# Check dependencies:
check_deps

# Build the proto files first (the examples will need them):
shopt -s globstar
build_messages messages/**/*.proto

# And then the examples:
run_command_in_examples "run build"

# Finally, record that we successfully ran a build:
mark

echo -e '\e[1;35m'"\nBuild Successful!"'\e[0m'
