#!/usr/bin/env bash

# Runs formatting checks on the server and client (without making changes).

# shellcheck source=scripts/common
. "$(dirname "${0}")/common" || { echo ERROR; exit 1; }

# In order to check formatting, we need regular and dev dependencies:
resolve_deps install install-dev

server_client_pair "isort -c ${ISORT_FLAGS}" "black --check --diff ." -- \
    "run check-formatting" -- "Checking formatting"
