#!/usr/bin/env bash

# Cleans build files in the project.
# Set SCRUB_VAR to the directory you wish to scrub or to nothing
# (`echo ${SCRUB_VAR}`=) to clean the project.

SCRUB_VAR=SCRUB

. "$(dirname "${0}")/common" || { echo ERROR; exit 1; }

# Remove files we know to be removable:
git clean -dX ${!SCRUB_VAR+"-f"} ${!SCRUB_VAR-"-i"}

# And then the env:
pipenv clean

# If we're scrubbing, delete the virtualenv too:
[ ! -z "${!SCRUB_VAR+x}" ] && pipenv --rm
