#!/usr/bin/env bash

# Formats the server and client.

# shellcheck source=scripts/common
. "$(dirname "${0}")/common" || { echo ERROR; exit 1; }

# In order to format, we need regular and dev dependencies:
resolve_deps install install-dev

server_client_pair "isort -y ${ISORT_FLAGS}" "black ." -- "run format" -- "Formatting"
