#!/usr/bin/env bash

# Grabs dependencies; preps for a build.

. "$(dirname "${0}")/common"

set -e

err() {
    echo -e '\e[1;31m'"${1}"'\e[0m' && exit "${2}"
}

if [ -f "${BUILD_SCRIPT_PATH}" ]; then
    "${BUILD_SCRIPT_PATH}" install
else
    err "Can't find build script; is it still at ${BUILD_SCRIPT_PATH}?" 1
fi

find_or_run "${BUILD_DIR}/.deps-installed" || {
    pipenv install --dev || rm "${BUILD_DIR}/.deps-installed"
}
