#!/usr/bin/env bash

# Grabs dev dependencies. Just a `pipenv install --dev` wrapper at the moment.

# shellcheck source=scripts/common
. "$(dirname "${0}")/common" || { echo ERROR; exit 1; }

# Note: This target handles dependency tracking itself!

# In order to install, we need our local dependencies to be installed:
resolve_deps local-deps

pipenv_dev_install() {
    pipenv install --dev && print "Dev Install Successful!" "$PURPLE";
}

# Next, pipenv:
PIP_IGNORE_INSTALLED=1 \
run_command_in_server pipenv_dev_install Pipfile "${marker}" ||
    err "Failed to install python dev dependencies." $?
