#!/usr/bin/env bash

# Grabs dependencies; preps for a build.

. "$(dirname "${0}")/common" || { echo ERROR; exit 1; }

# First make sure we've got our local dependencies installed:
check_deps

# Then install deps for all the examples:
run_command_in_examples "install"

# Next, pipenv:
pipenv install

# Finally, record that we successfully installed:
mark

echo -e '\e[1;35m'"\nInstall Successful!"'\e[0m'
