#!/usr/bin/env bash

# Runs the server and client's respective linters.

. "$(dirname "${0}")/common" || { echo ERROR; exit 1; }

# In order to lint, we need regular and dev dependencies to have built:
resolve_deps install install-dev build

server_client_pair "mypy server" -- "run lint" -- "Linting"
