#!/usr/bin/env bash

# Builds containers for the project.

# shellcheck source=scripts/common
. "$(dirname "${0}")/common" || { echo ERROR; exit 1; }

# To build the containers, we only really need docker:
check_local_dep docker \
    "running the script here: https://github.com/docker/docker-install"

cp .gitignore .dockerignore

readonly COMMIT_SHA=$(git rev-parse HEAD || echo "unknown")

readonly DOCKER_FLAGS="${DOCKER_FLAGS} \
    --build-arg CORES=$(nproc)
    --build-arg PACKAGE_DIR=${PACKAGE_DIR} \
    --build-arg BUILD_DIR=${BUILD_DIR} \
    --build-arg EXC_NAME=${EXC_NAME} \
    --build-arg VERSION=${VERSION} \
    --build-arg HOST=${HOST-0.0.0.0} \
    --build-arg PORT=${PORT-5000} \
    --build-arg VERSION=${VERSION-0.0.0} \
    --build-arg COMMIT_SHA=${COMMIT_SHA-unknown} \
"

# $1: stage name
# shellcheck disable=SC2086
build_stage() { docker build ${DOCKER_FLAGS} --target "${1}" -t "${EXC_NAME}-${1}" .; }

build_stage base
build_stage build
build_stage check
build_stage test
build_stage package
build_stage dist

docker tag "${EXC_NAME}-dist" "${EXC_NAME}-dist:latest"
docker tag "${EXC_NAME}-dist" "${EXC_NAME}-dist:${VERSION}"

if is_set UPLOAD_COV; then
    docker run \
        -e "CODECOV_TOKEN=${CODECOV_TOKEN-0}" \
        -e "COVERALLS_SERVICE_NAME=${COVERALLS_SERVICE_NAME-0}" \
        -e "COVERALLS_REPO_TOKEN=${COVERALLS_REPO_TOKEN-0}" \
        -e "COVERALLS_SERVICE_JOB_ID=${COVERALLS_SERVICE_JOB_ID-0}" \
        -e "COVERALLS_RUN_AT=${COVERALLS_RUN_AT}" \
        -e "COVERALLS_PARALLEL=${COVERALLS_PARALLEL-0}" \
        -it "${EXC_NAME}-test" \
        pipenv run upload-cov
fi

if is_set CHECK_SCRIPTS; then
    docker run -it "${EXC_NAME}-build" \
        pipenv run check-scripts
fi

print "All done!" "${CYAN}"
