#!/usr/bin/env bash

# Runs tests for the server and client.

. "$(dirname "${0}")/common" || { echo ERROR; exit 1; }

# In order to test, we need regular and dev dependencies and to have built:
resolve_deps install install-dev build

server_client_pair "pytest ${TESTS_DIR}" -- "run test" -- "Testing"
