#!/usr/bin/env bash

# Runs tests for the server and client.

# shellcheck source=scripts/common
. "$(dirname "${0}")/common" || { echo ERROR; exit 1; }

# In order to test, we need regular and dev dependencies and to have built:
resolve_deps install install-dev build

mkdir -p "${COVERAGE_DIR}"
COV_DIR="$(realpath "${COVERAGE_DIR}")"

server_client_pair "pytest --cov=${SERVER_DIR} ${PYTEST_COV_FLAGS} ${TESTS}" -- "run test -- --coverageDirectory ${COV_DIR}" -- "Testing"
