#!/usr/bin/env bash

# Runs a command after installing the dev dependencies for the project.

. "$(dirname "${0}")/common"

# First, install the dev dependencies.
find_or_run "${BUILD_DIR}/.dev-deps-installed" || {
    pipenv install --dev || rm "${BUILD_DIR}/.dev-deps-installed"
}

# Run the command!
"${@}"
