#!/usr/bin/env bash

# Runs a command after installing it's dependencies.

. "$(dirname "${0}")/common" || { echo ERROR; exit 1; }

deps=()
command=""

# Parse the args:
i=1
for arg in "${@}"; do
    ((i++))

    [[ "${arg}" == -- ]] && {
        command="${@:$i}"
        break;
    }

    deps+=($"${arg}")
done

# Resolve the dependencies:
for dep_name in "${deps[@]}"; do
    # If a dependency's marker file doesn't exist..
    [ -f "$(marker_file "${dep_name}")" ] || {
        # ..run its script:
        echo -e '\e[1;34m'"Resolving ${dep_name}:"'\e[0m'
        ("$(script_file "${dep_name}")") || {
            err "Failed to resolve ${dep_name}!" $?
        }
        echo
    }
done

# Finally, run the command!
${command[@]}
