#!/usr/bin/env bash

# Runs a set of commands after resolving their dependencies.

# shellcheck source=scripts/common
. "$(dirname "${0}")/common" || { echo ERROR; exit 1; }

deps=()
command=""

# Parse the args:
i=1
for arg in "${@}"; do
    ((i++))

    [[ "${arg}" == -- ]] && {
        command=("${@:$i}")
        break;
    }

    deps+=("${arg}")
done

# Resolve the dependencies:
resolve_deps "${deps[@]}"

dprint "deps: ${deps[*]}, commands: ${command[*]}"

# Finally, run the commands!
for cmd in "${command[@]}"; do
    script_file="$(script_file "${cmd}")"

    if [ -f "${script_file}" ]; then
        dprint "Running ${cmd} as a script (${script_file}).."

        # If a matching script file exists, run it:
        ("${script_file}") || err "Script \`${cmd}\` failed with $?." $?
    else
        dprint "Running ${cmd} as a command.."

        # Otherwise, run the command:
        $cmd || err "\`${cmd}\` failed with $?." $?
    fi
done
